[package]
name = "rinha-rust-warp"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.42.0"
bytes = "1.10.1"
futures-util = "0.3.31"
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
warp = "0.3.7"
